Recipes/Controllers/CocktailsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Recipes.Models;

namespace Recipes.Controllers
{
    public class CocktailsController : Controller
    {
        private readonly ApiCocktails _apiDrinks = new ApiCocktails();
        [HttpGet]
        public IActionResult Index()
        {
            Categories.DrinkCategory mc = new() { drinks = _apiDrinks.GetRandomCocktails(new(), 20).Result, categories = _apiDrinks.GetCocktailCategories(new()).Result };
            return View(mc.drinks);
        }
        [HttpGet, HttpPost]
        public IActionResult CocktailRecipe(string id)
        {
            if (id == null)
                return RedirectToAction("Index");
            var item = _apiDrinks.GetCocktailById(new(), id).Result;
            if (item == null)
                return RedirectToAction("Index");
            return View(item);
        }
        [HttpGet, HttpPost]
        public IActionResult SearchDrinks(string name)
        {
            if (name == null)
                return RedirectToAction("Index");
            CocktailItems? items = _apiDrinks.GetCocktailByName(new(), name).Result;
            if (items == null)
                return RedirectToAction("Index");
            return View(items);
        }
        [HttpGet("/[controller]/MealCategory/{id}")]
        public IActionResult CocktailCategory([FromRoute] string id)
        {
            if (id == null)
                return RedirectToAction("Index");
            Categories.Catwithdrinks? cwm = _apiDrinks.GetCocktailsByCategory(new(), id).Result;
            if (cwm == null)
                return RedirectToAction("Index");
            return View(cwm);
        }
    }
}

Recipes/Controllers/MealsController.cs
using Microsoft.AspNetCore.Mvc;
using Recipes.Models;

namespace Recipes.Controllers
{
    public class MealsController : Controller
    {
        private readonly ApiMeals _apiMeals = new ApiMeals();
        [HttpGet]
        public IActionResult Index()
        {
            Categories.MealCategory mc = new() { meals = _apiMeals.GetRandomMeals(new(), 20).Result , categories = _apiMeals.GetMealCategories(new()).Result};
            return View(mc);
        }
        [HttpGet,HttpPost]
        public IActionResult MealRecipe(string id)
        {
            if(id == null)
                return RedirectToAction("Index");
            var meal = _apiMeals.GetMealById(new(), id).Result;
            if (meal == null)
                return RedirectToAction("Index");
            return View(meal);
        }
        [HttpGet,HttpPost]
        public IActionResult SearchMeal(string name)
        {
            if(name == null)
                return RedirectToAction("Index");
            MealItems? meals = _apiMeals.GetMealByName(new(), name).Result;
            if(meals == null)
                return RedirectToAction("Index");
            return View(meals);
        }
        [HttpGet("/[controller]/MealCategory/{id}")]
        public IActionResult MealCategory([FromRoute] string id)
        {
            if(id == null)
                return RedirectToAction("Index");
            Categories.Catwithmeals? cwm = _apiMeals.GetMealsByCategory(new(), id).Result;
            if(cwm == null)
                return RedirectToAction("Index");
            return View(cwm);
        }
    }
}

Recipes/Views/Shared/Components/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Recipes.Models;

namespace Recipes.Views.Shared.Components
{
    public class CategoriesViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string type)
        {
            return View(type);
        }
    }
}

Recipes/Views/Shared/Components/ProfileViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Recipes.Core;
using System.Web;
using Recipes.Models;

namespace Recipes.Views.Shared.Components
{
    public class ProfileViewComponent : ViewComponent
    {
        private UserDbContext _context;
        string userId;
        public ProfileViewComponent(UserDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(string type)
        {
            userId = Request.Cookies["userId"];
            var user = _context.GetUser(userId);
            if(user != null)
                ViewBag.User = user;
            return View(type);
        }
    }
}

Recipes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Recipes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Recipes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Recipes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" asp-area="" asp-controller="Meals" asp-action="Index" data-bs-toggle="dropdown" aria-expanded="false">
                                Meals
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Meals" asp-action="index">Home</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                @await Component.InvokeAsync("Categories", new{type = "meal"})
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" asp-area="" asp-controller="Cocktails" asp-action="Index" data-bs-toggle="dropdown" aria-expanded="false">
                                Cocktails
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Cocktails" asp-action="index">Home</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                @await Component.InvokeAsync("Categories",new{type = "cocktail"})
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            @await Component.InvokeAsync("Profile", new { type = "Profile" })
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Recipes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>